---
# Política 20: OTel Collector puede enviar trazas a Jaeger y resolver DNS
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-otel-egress
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: otel-collector
  policyTypes:
    - Egress
  egress:
    # Envío de trazas a Jaeger
    - to:
        - podSelector:
            matchLabels:
              app: jaeger
      ports:
        - port: 4317
          protocol: TCP
        - port: 4318
          protocol: TCP
        - port: 14268
          protocol: TCP
    # Resolución DNS (sin esto el FQDN de jaeger-collector no resuelve)
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
